
# Social links
twitter-handle: its_lifeofash
instagram-handle: its_lifeofash
youtube-handle: UCTfIKRuj4GcoUif52nd541g

# Website settings
title: thelifeofash
author: Ash
favicon: 📝
permalink: /:categories/:title/
excerpt_separator: <!-- more -->

# Jekyll settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-target-blank

# Jekyll Sitemap settings
url: "https://thelifeofash.com"

# Jekyll Feed settings
feed:
  posts_limit: 14

# Jekyll Compress Layout settings
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

# Files that should not be copied to the _site directory on build
exclude:
  - PROGRESS.md
  - README.md
