
# Social links
twitter-handle: its_lifeofash
instagram-handle: its_lifeofash

# Website settings
title: thelifeofash
author: Ash
favicon: 📝
permalink: /:categories/:title/

# Jekyll settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-compose
  - jekyll-target-blank

# Jekyll Sitemap settings
url: "https://thelifeofash.com"

# Jekyll Compose settings
jekyll_compose:
  auto_open: true
  default_front_matter:
    drafts:
      layout: post
      author: Ash
      categories: default
      tags: personal
      worktime: 0
    posts:
      author: Ash
      categories: default
      tags: personal
      published: false

# Jekyll Feed settings
feed:
  posts_limit: 14

# Jekyll Compress Layout settings
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

# Files that should not be copied to the _site directory on build
exclude:
  - PROGRESS.md
